booktique/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main, about, create_product, edit_product, delete_product
from main.views import show_xml, show_json, show_xml_by_id, show_json_by_id
from main.views import register, login_user, logout_user
from main.views import add_product_ajax, create_product_flutter, edit_product_flutter, delete_product_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create_product/', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<uuid:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<uuid:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit_product/<uuid:id>/', edit_product, name='edit_product'),
    path('delete_product/<uuid:id>/', delete_product, name='delete_product'),
    path('about/', about, name='about'),
    path('create_product_ajax/', add_product_ajax, name='add_product_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
    path('edit-product-flutter/<uuid:id>/', edit_product_flutter, name='edit_product_flutter'),
    path('delete-product-flutter/<uuid:id>/', delete_product_flutter, name='delete_product_flutter'),
    
]

main/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    description = models.TextField()
    stock_quantity = models.IntegerField()
    price = models.IntegerField()

    def __str__(self):
        return self.name

main/forms.py
from django import forms
from .models import Product
from django.utils.html import strip_tags

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'author', 'description', 'stock_quantity', 'price']

    def clean_name(self):
        name = self.cleaned_data['name']
        return strip_tags(name)
    
    def clean_author(self):
        author = self.cleaned_data['author']
        return strip_tags(author)
    
    def clean_description(self):
        description = self.cleaned_data['description']
        return strip_tags(description)

main/views.py
import datetime
import json
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core import serializers
from django.shortcuts import render, redirect
from main.models import Product
from main.forms import ProductForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.utils.html import strip_tags

@login_required(login_url='/login')
def show_main(request):
    query = request.GET.get('query')
    if query:
        results = Product.objects.filter(name__icontains=query)  # Adjust the filter as needed

    context = {
        'name': request.user.username,
        'class': 'PBP B',
        'npm': '2306165553',
        'last_login': request.COOKIES.get('last_login', 'Never'),
    }

    return render(request, "main.html", context)

def about(request):
    return render(request, "about.html")

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return redirect('main:show_main')

    context = {'form': form}
    return render(request, "create_product.html", context)

def edit_product(request, id):
    product = Product.objects.get(pk = id)
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def delete_product(request, id):
    product = Product.objects.get(pk = id)
    product.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

def show_xml(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            user = form.get_user()
            login(request, user)
            response = HttpResponseRedirect(reverse('main:about'))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.error(request, 'Invalid username or password. Please try again.')  # Tambahkan pesan kesalahan di sini

    else:
        form = AuthenticationForm(request)
    
    context = {'form': form}
    return render(request, 'login.html', context)


def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

@csrf_exempt
@require_POST
def add_product_ajax(request):
    name = strip_tags(request.POST.get('name'))
    author = strip_tags(request.POST.get('author'))
    description = strip_tags(request.POST.get('description'))
    stock_quantity = request.POST.get('stock_quantity')
    price = request.POST.get('price')
    user = request.user

    new_product = Product(name=name, author=author, description=description, stock_quantity=stock_quantity, price=price, user=user)
    new_product.save()

    return HttpResponse(b"CREATED", status=201)

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)
        new_mood = Product.objects.create(
            user=request.user,
            name=data['name'],
            author=data['author'],
            description=data['description'],
            stock_quantity=data['stock_quantity'],
            price=data['price'],
        )

        new_mood.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

@csrf_exempt
def delete_product_flutter(request, id):
    if request.method == 'GET':  # Changed from checking POST
        try:
            product = Product.objects.get(pk=id)
            product.delete()
            return JsonResponse({"status": "success"}, status=200)
        except Product.DoesNotExist:
            return JsonResponse(
                {"status": "error", "message": "Product not found"}, 
                status=404
            )
        except Exception as e:
            return JsonResponse(
                {"status": "error", "message": str(e)}, 
                status=500
            )
    
    return JsonResponse(
        {"status": "error", "message": "Invalid method"}, 
        status=405
    )

@csrf_exempt
def edit_product_flutter(request, id):
    if request.method == 'POST':
        try:
            product = Product.objects.get(pk=id)
            data = json.loads(request.body)
            
            # Update fields
            product.name = data['name']
            product.author = data['author']
            product.description = data['description']
            product.stock_quantity = int(data['stock_quantity'])
            product.price = int(data['price'])
            
            product.save()
            return JsonResponse({"status": "success"}, status=200)
        except Product.DoesNotExist:
            return JsonResponse({"status": "error", "message": "Product not found"}, status=404)
        except Exception as e:
            return JsonResponse({"status": "error", "message": str(e)}, status=500)
    
    return JsonResponse({"status": "error", "message": "Invalid method"}, status=405)

   

main/templates/about.html
{% extends 'base.html' %}
{% block meta %}
<title>Booktique - About</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}
<!-- Hero Section -->
<section class="bg-blue-200 text-blue-950 py-20">
    <div class="max-w-4xl mx-auto text-center">
        <h1 class="text-4xl font-bold mb-4 animate-bounce">Welcome to Booktique!</h1>
        <p class="mb-6 text-lg">Your one-stop e-commerce platform for all things books.</p>
        <a href="{% url 'main:show_main' %}">
            <button class="py-2 px-4 bg-blue-950 text-white rounded-full hover:bg-slate-950 transition transform hover:scale-105">
                View Products
            </button>
        </a>
    </div>
</section>

<!-- About and Contact Section -->
<div class="max-w-4xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-6 p-6">
    <!-- About Us Card -->
    <div class="bg-white rounded-lg shadow-md transition-transform transform hover:scale-105 p-4">
        <h2 class="mt-6 text-lg font-semibold">About Us</h2>
        <p id="about-text" class="mt-2 overflow-hidden max-h-20 text-ellipsis cursor-pointer" onclick="toggleAboutModal()">At Booktique, we are passionate about connecting book lovers with their next great read. 
           Whether you’re searching for bestsellers, rare finds, or just looking to explore, we have something for everyone!</p>
        <button class="text-blue-600 hover:underline mt-2" onclick="toggleAboutModal()">Show More</button>
    </div>

    <!-- Contact Us Card -->
    <div class="bg-white rounded-lg shadow-md transition-transform transform hover:scale-105 p-4">
        <h2 class="mt-6 text-lg font-semibold">Contact Us</h2>
        <p class="mt-2 overflow-hidden max-h-20 text-ellipsis">We would love to hear from you! Feel free to reach out with any questions or feedback.</p>
        <ul class="mt-2">
            <li>Email: <a href="mailto:info@booktique.com" class="text-blue-600 hover:underline">info@booktique.com</a></li>
            <li>Phone: <a href="tel:+62234567890" class="text-blue-600 hover:underline">+62 (234) 567-890</a></li>
        </ul>
    </div>
</div>

<!-- Modal About Us -->
<div id="about-modal" class="fixed inset-0 flex items-center justify-center bg-black bg-opacity-50 hidden">
    <div class="bg-white rounded-lg p-6 max-w-md mx-auto">
        <h2 class="text-lg font-semibold">About Us</h2>
        <p class="mt-2">At Booktique, we are passionate about connecting book lovers with their next great read. 
           Whether you’re searching for bestsellers, rare finds, or just looking to explore, we have something for everyone!</p>
        <button class="mt-4 py-2 px-4 bg-blue-950 text-white rounded hover:bg-blue-700" onclick="toggleAboutModal()">Close</button>
    </div>
</div>

<!-- Social Media Section -->
<div class="max-w-4xl mx-auto p-6 bg-slate-950 rounded-lg shadow-md mt-6 text-center transition-transform transform hover:scale-105">
    <h2 class="mt-6 text-white text-lg font-semibold">Follow Us</h2>
    <div class="flex justify-center space-x-4 mt-2">
        <a href="https://instagram.com/" class="text-white hover:underline transition duration-300">Instagram</a>
        <a href="https://facebook.com/" class="text-white hover:underline transition duration-300">Facebook</a>
        <a href="https://twitter.com/" class="text-white hover:underline transition duration-300">Twitter</a>
    </div>
</div>

<script>
    function toggleAboutModal() {
        const modal = document.getElementById('about-modal');
        modal.classList.toggle('hidden');
    }
</script>

{% endblock content %}

main/templates/card_info.html
{% load static %}
<div class="relative break-inside-avoid w-full max-w-lg mx-auto p-4 sm:p-8">
    <div class="bg-blue-100 shadow-lg rounded-2xl mb-6 p-4 sm:p-8 border-2 border-transparent transition-transform duration-300 transform hover:scale-105">
        <div class="flex flex-col sm:flex-row items-center mb-4">
            <div class="h-20 w-20 flex items-center justify-center bg-white rounded-full mb-4 sm:mb-0 sm:mr-4">
                <img src="{% static 'image/photo_profile.jpg' %}" alt="Profile Image" class="h-20 w-20 rounded-full object-cover">
            </div>
            <div class="text-center sm:text-left">
                <h3 class="font-bold text-2xl sm:text-3xl text-blue-950">{{ name }}</h3>
                <p class="text-blue-950">{{ npm }}</p>
            </div>
        </div>
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div class="flex flex-col items-center">
                <span class="text-blue-950 text-sm font-bold mb-2">Class</span> 
                <span class="bg-white text-blue-950 text-lg font-medium px-3 py-1 rounded-2xl">
                    {{ class }}
                </span>
            </div>
            <div class="flex flex-col items-center">
                <span class="text-blue-950 text-sm font-bold mb-2">Last Login</span> 
                <span class="bg-white text-blue-950 text-lg font-medium px-3 py-1 rounded-2xl">
                    {{ last_login }}
                </span>
            </div>
        </div>
    </div>
</div>

main/templates/card_product.html
<div class="flex flex-wrap justify-center">
    <!-- Product Card -->
    <div class="relative break-inside-avoid w-full h-full sp-6 animate-fadeIn">
        <div class="relative top-5 bg-white shadow-md rounded-2xl mb-6 break-inside-avoid flex flex-col border-2 border-gray-300 transition-transform duration-300 h-full hover:scale-105">
            <!-- Product Information -->
            <div class="bg-blue-100 text-gray-800 p-4 rounded-t-2xl border-b-2 border-gray-300 flex flex-col flex-grow">
                <h3 class="font-bold text-center text-2xl mb-1">{{ product.name }}</h3>
                <div class="flex items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-600" viewBox="0 0 20 20" fill="currentColor">
                        <path d="M10 3a7 7 0 100 14 7 7 0 000-14zM1 17a9 9 0 0118 0H1z" />
                    </svg>
                    <p class="text-gray-600 ml-2">{{ product.author }}</p>
                </div>
            </div>

            <!-- Product Stock and Price -->
            <div class="p-4 flex-grow">
                <div class="grid grid-cols-2 gap-4">
                    <div class="flex flex-col items-center">
                        <span class="text-gray-600 text-sm font-bold text-center">Stock</span>
                        <span class="inline-block bg-green-200 text-green-800 text-lg font-medium px-2.5 py-0.5 rounded-full flex-grow text-center">
                            {{ product.stock_quantity }}
                        </span>
                    </div>
                    <div class="flex flex-col items-center">
                        <span class="text-gray-600 text-sm font-bold text-center">Price</span>
                        <span class="inline-block bg-yellow-200 text-yellow-800 text-lg font-medium px-2.5 py-0.5 rounded-full flex-grow text-center">
                            ${{ product.price }}
                        </span>
                    </div>
                </div>

                <!-- Product Description -->
                <p class="mt-4 text-gray-700 overflow-hidden text-ellipsis" style="max-height: 50px; overflow: hidden;">
                    {{ product.description }}
                </p>

                <!-- Show More Button -->
                <button type="button" class="mt-4 text-blue-600 hover:underline" onclick="showDescriptionModal(this)" data-name="{{ product.name }}" data-author="{{ product.author }}" data-stock="{{ product.stock_quantity }}" data-price="{{ product.price }}" data-description="{{ product.description }}">
                    Show More
                </button>
            </div>

            <!-- Edit & Delete Buttons -->
            <div class="flex justify-center p-4 space-x-4 border-t-2 border-gray-300">
                <a href="{% url 'main:edit_product' product.id %}" class="bg-blue-950 hover:bg-slate-900 text-white rounded-lg p-2 transition duration-300 flex items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                        <path d="M12.586 2.586a2 2 0 012.828 2.828l-8 8a1 1 0 01-.293.207l-3 1a1 1 0 01-1.207-1.207l1-3a1 1 0 01.207-.293l8-8z" />
                    </svg>
                    <span class="ml-1">Edit</span>
                </a>
                <a href="{% url 'main:delete_product' product.id %}" class="bg-red-900 hover:bg-red-950 text-white rounded-lg p-2 transition duration-300 flex items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                        <path fill-rule="evenodd" d="M4 4a1 1 0 011-1h10a1 1 0 011 1v1H4V4zM4 6h12v12a2 2 0 01-2 2H6a2 2 0 01-2-2V6z" clip-rule="evenodd" />
                    </svg>
                    <span class="ml-1">Delete</span>
                </a>
            </div>
        </div>
    </div>
</div>

<!-- Modal Product Details -->
<div id="description-modal" class="fixed inset-0 flex items-center justify-center bg-black bg-opacity-50 hidden z-50">
    <div class="bg-white rounded-lg p-6 max-w-md w-full mx-auto overflow-hidden" style="max-height: 80vh; overflow-y: auto;">
        <!-- Product Information Modal -->
        <h3 class="font-bold text-2xl mb-1"></h3>
        <div class="flex items-center mb-4">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-600" viewBox="0 0 20 20" fill="currentColor">
                <path d="M10 3a7 7 0 100 14 7 7 0 000-14zM1 17a9 9 0 0118 0H1z" />
            </svg>
            <p class="text-gray-600 ml-2 modal-author"></p>
        </div>

        <!-- Stock & Price Modal -->
        <div class="grid grid-cols-2 gap-4 mb-4">
            <div class="flex flex-col items-center">
                <span class="text-gray-600 text-sm font-bold text-center">Stock</span>
                <span class="inline-block bg-green-200 text-green-800 text-lg font-medium px-2.5 py-0.5 rounded-full flex-grow text-center modal-stock"></span>
            </div>
            <div class="flex flex-col items-center">
                <span class="text-gray-600 text-sm font-bold text-center">Price</span>
                <span class="inline-block bg-yellow-200 text-yellow-800 text-lg font-medium px-2.5 py-0.5 rounded-full flex-grow text-center modal-price"></span>
            </div>
        </div>

        <!-- Description with Scroll -->
        <div class="overflow-auto max-h-[300px] mb-4">
            <p class="text-gray-700 modal-description"></p>
        </div>

        <!-- Edit & Delete Buttons  -->
        <div class="flex justify-center space-x-4 mb-4 border-t-2 border-gray-300 pt-4">
            <a href="{% url 'main:edit_product' product.id %}" class="bg-blue-950 hover:bg-slate-900 text-white rounded-lg px-4 py-2 transition duration-300 flex items-center">
                Edit
            </a>
            <a href="{% url 'main:delete_product' product.id %}" class="bg-red-900 text-white rounded-lg px-4 py-2">
                Delete
            </a>
        </div>

        <!-- Close Button -->
        <button class="py-2 px-4 bg-gray-600 text-white rounded hover:bg-gray-800 w-full" onclick="hideDescriptionModal()">Close</button>
    </div>
</div>

<script>
    function showDescriptionModal(button) {
        const modal = document.getElementById('description-modal');
        
        // Get data from button attributes
        const name = button.getAttribute('data-name');
        const author = button.getAttribute('data-author');
        const stock = button.getAttribute('data-stock');
        const price = button.getAttribute('data-price');
        const description = button.getAttribute('data-description');
        
        // Update modal content
        modal.querySelector('h3').textContent = name;
        modal.querySelector('.modal-author').textContent = author;
        modal.querySelector('.modal-stock').textContent = stock;
        modal.querySelector('.modal-price').textContent = `$${price}`;
        modal.querySelector('.modal-description').textContent = description;
        
        // Show modal
        modal.classList.remove('hidden');
    }

    function hideDescriptionModal() {
        document.getElementById('description-modal').classList.add('hidden');
    }
</script>

<style>
    @keyframes fadeIn {
        from {
            opacity: 0;
        }
        to {
            opacity: 1;
        }
    }

    .animate-fadeIn {
        animation: fadeIn 1s ease-in-out;
    }
</style>

main/templates/create_product.html
{% extends 'base.html' %}

{% block meta %}
<title>Add New Product - Booktique</title>
{% endblock meta %}

{% block content %}
<h1>Add New Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Product"/>
            </td>
        </tr>
    </table>
</form>

<br />

<a href="{% url 'main:show_main' %}">
    <button>Back to Product List</button>
</a>

{% endblock content %}

main/templates/edit_product.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Edit Product - Booktique</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}
<div class="flex flex-col min-h-screen bg-gray-100">
  <div class="container mx-auto px-4 py-8 mt-16 max-w-xl">
    <h1 class="text-3xl font-bold text-center mb-8 text-black">Edit Product</h1>
  
    <div class="bg-white rounded-lg p-6 form-style">
      <form method="POST" class="space-y-6">
          {% csrf_token %}
          {% for field in form %}
              <div class="flex flex-col">
                  <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-gray-700">
                      {{ field.label }}
                  </label>
                  <div class="w-full">
                      {{ field }}
                  </div>
                  {% if field.help_text %}
                      <p class="mt-1 text-sm text-gray-500">{{ field.help_text }}</p>
                  {% endif %}
                  {% for error in field.errors %}
                      <p class="mt-1 text-sm text-red-600">{{ error }}</p>
                  {% endfor %}
              </div>
          {% endfor %}
        <div class="flex justify-center mt-6">
            <button type="submit" class="text-white font-semibold px-6 py-3 rounded-lg transition duration-300 ease-in-out w-full bg-blue-950 hover:bg-slate-900">
                Update Product
            </button>
        </div>
      </form>
  </div>

  <div class="flex justify-center mt-4">
      <a href="{% url 'main:show_main' %}" class="bg-gray-600 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out">
          Back to Product List
      </a>
  </div>
  </div>
</div>
{% endblock content %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}
<div class="min-h-screen flex items-center justify-center w-screen bg-gray-100 py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full space-y-8">
    <div>
      <h2 class="mt-6 text-center text-black text-3xl font-extrabold text-gray-900">
        Login to your account
      </h2>
    </div>
    <form class="mt-8 space-y-6" method="POST" action="">
      {% csrf_token %}
      <input type="hidden" name="remember" value="true">
      <div class="rounded-md shadow-sm -space-y-px">
        <div>
          <label for="username" class="sr-only">Username</label>
          <input id="username" name="username" type="text" required class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-blue-950 focus:border-blue-950 focus:z-10 sm:text-sm" placeholder="Username">
        </div>
        <div>
          <label for="password" class="sr-only">Password</label>
          <input id="password" name="password" type="password" required class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-blue-950 focus:border-blue-950 focus:z-10 sm:text-sm" placeholder="Password">
        </div>
      </div>

      <div>
        <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-blue-950 hover:bg-slate-950 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-950">
          Sign in
        </button>
      </div>
    </form>

    {% if messages %}
    <div class="mt-4">
      {% for message in messages %}
      {% if message.tags == "success" %}
            <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% elif message.tags == "error" %}
            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% else %}
            <div class="bg-blue-100 border border-blue-400 text-blue-700 px-4 py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% endif %}
      {% endfor %}
    </div>
    {% endif %}

    <div class="text-center mt-4">
      <p class="text-sm text-black">
        Don't have an account yet?
        <a href="{% url 'main:register' %}" class="font-medium text-blue-500 hover:text-blue-700">
          Register Now
        </a>
      </p>
    </div>
  </div>
</div>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Register</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}
<div class="min-h-screen flex items-center justify-center bg-gray-100 py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full space-y-8 form-style">
    <div>
      <h2 class="mt-6 text-center text-3xl font-extrabold text-black">
        Create your account
      </h2>
    </div>
    <form class="mt-8 space-y-6" method="POST">
      {% csrf_token %}
      <input type="hidden" name="remember" value="true">
      <div class="rounded-md shadow-sm -space-y-px">
        {% for field in form %}
          <div class="{% if not forloop.first %}mt-4{% endif %}">
            <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-black">
              {{ field.label }}
            </label>
            <div class="relative">
              {{ field }}
              <div class="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
                {% if field.errors %}
                  <svg class="h-5 w-5 text-red-500" fill="currentColor" viewBox="0 0 20 20">
                    <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clip-rule="evenodd" />
                  </svg>
                {% endif %}
              </div>
            </div>
            {% if field.errors %}
              {% for error in field.errors %}
                <p class="mt-1 text-sm text-red-600">{{ error }}</p>
              {% endfor %}
            {% endif %}
          </div>
        {% endfor %}
      </div>

      <div>
        <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-blue-950 hover:bg-slate-950 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-950">
          Register
        </button>
      </div>
    </form>

    {% if messages %}
    <div class="mt-4">
      {% for message in messages %}
      {% if message.tags == "success" %}
        <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="alert">
          <span class="block sm:inline">{{ message }}</span>
        </div>
      {% elif message.tags == "error" %}
        <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
          <span class="block sm:inline">{{ message }}</span>
        </div>
      {% else %}
        <div class="bg-blue-100 border border-blue-400 text-blue-700 px-4 py-3 rounded relative" role="alert">
          <span class="block sm:inline">{{ message }}</span>
        </div>
      {% endif %}
      {% endfor %}
    </div>
    {% endif %}

    <div class="text-center mt-4">
      <p class="text-sm text-black">
        Already have an account?
        <a href="{% url 'main:login' %}" class="font-medium text-blue-500 hover:text-blue-700">
          Login here
        </a>
      </p>
    </div>
  </div>
</div>
{% endblock content %}